services:
  web-dev:
    build:
      context: .
      target: development
    command:
      - sh
      - -c
      - pnpm exec prisma generate && pnpm exec next dev --hostname 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - pnpm-store:/pnpm/store
      - node-modules:/app/node_modules

  web-prod:
    build:
      context: .
      target: runner
    command:
      - pnpm
      - start:web
    ports:
      - "3000:3000"
    env_file:
      - .env.docker

  parser-job:
    build:
      context: .
      target: runner
    entrypoint:
      - node
      - dist/parser-batch-job.mjs
    env_file:
      - .env.docker
    profiles:
      - jobs

  persistence-job:
    build:
      context: .
      target: runner
    entrypoint:
      - node
      - dist/persistence-batch-job.mjs
    env_file:
      - .env.docker
    profiles:
      - jobs

volumes:
  pnpm-store:
  node-modules:
