import type { Metadata } from "next";
import { Inter, DM_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "src/components/theme-provider";
import { Toaster } from "src/components/ui/toast";
import { TooltipProvider } from "src/components/ui/tooltip";
import { cn } from "src/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CompanyProvider } from "src/contexts/company-context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        inter.variable,
        dmMono.variable
      )}
    >
      <body className="min-h-full flex flex-col font-sans tracking-tight selection:bg-primary selection:text-primary-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <CompanyProvider>
            <TooltipProvider>
              <Toaster>{children}</Toaster>
            </TooltipProvider>
          </CompanyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
